<?php
/**
 * @var $block \Magenest\ShopByBrand\Block\Group\SideBar
 */

$datas = $block->getGroupInfo();
$baseBrandUrl = $block->getBaseGroupUrl();

?>

<div class="mn-brand-filter">
    <h3 class='brand-heading_title'>Group Brand Filter</h3>
    <div class="mn-items" >
        <?php foreach ($datas as $data) : ?>
            <div class="mn-item">
                <a class="brand-name" href='<?php echo $baseBrandUrl.'/'.$data['url_key'] ?>' ><?php echo $data['name'] ?> (<?php echo $block->getQtyBrand($data['group_id']) ?>)</a>
            </div>
        <?php endforeach; ?>
    </div>
</div>
