<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading"
                aria-level="2"><?= $block->escapeHtml(__('THIS IS EXAMPLE ABOUT AJAX')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <div
                    class="field note"><?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?></div>
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="login[username]"
                               value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                               id="email" type="email" class="input-text"
                               title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                               data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="login[password]"
                               type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                               class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                               data-validate="{required:true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" class="action login primary" name="send" id="send2">
                            <span><?= $block->escapeHtml(__('Sign In')) ?></span></button>
                    </div>
                    <div class="secondary"><a class="action remind"
                                              href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
    <div class="col-m-6" id="popup-mpdal" style="display:none;">
    </div>
</div>
<script>

    //    require([
    //        'jquery',
    //        'Magento_Ui/js/modal/alert'
    //        //day la modal cua magento. xem them o day: http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/widgets/widget_alert.html
    //        // ngoai ra co 1 loai hay dc su dung nua la Magento_Ui/js/modal/modal. loai nay nang cao hon va su dung vao nhieu muc dich hon
    //        // xem them o day. http://devdocs.magento.com/guides/v2.0/javascript-dev-guide/widgets/widget_modal.html
    //        // BAI TAP VE NHA LA SU DUNG Magento_Ui/js/modal/modal thay the cho Magento_Ui/js/modal/alert => MAI NOP
    //    ], function ($,      //bien thay the 'jquery'
    //                 alert   //bien nay thay the 'Magento_Ui/js/modal/alert'
    //    ) {
    //        $('#send2').on('click', function (e) { //su kien click vao element co id='send2'
    //                //ngan k cho form submit
    //                $('#login-form').submit(function () {
    //                    return false;
    //                });
    //                //day la phan ajax
    //                var url = '<?php ///* @escapeNotVerified */ echo $block->getUrl('myajax/ajax/handle');?>//';
    //                var email = $('#email').val();
    //                var param = {email: email};
    //
    //                $.ajax({
    //                    showLoader: true,
    //                    url: url,
    //                    data: param,
    //                    type: "POST",
    //                    dataType: 'json'
    //                }).done(function (data) {
    //                    console.log(data)
    //                    // var data2 = JSON.parse(data);
    //                    console.log(data.message);
    //                    //phan modal
    //                    alert({
    //                        title: "Some title",//day la title
    //                        content: "this is content " + data.message,//day la content
    //                        actions: {
    //                            always: function () {
    //                                console.log('sau khi click vao OK se chay vao cai nay')
    //                            }
    //                        }
    //                    });
    //                })
    //
    //            }
    //        )
    //    });

    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function ($, modal) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Magenest part-time test',
                buttons: [{
                    text: $.mage.__('OK'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-mpdal'));
            $("#send2").on('click', function () {
            
                $('#login-form').submit(function () {
                    return false;
                });
                var email = $('#email').val();

                $.ajax({
                    type: "get",
                    url: "<?php echo $block->getUrl('myajax/ajax/handle') ?>",
                    data: 'email=' + email,
                    success: function (data) {
                        $('#popup-mpdal').html(data);
                    }
                });
                $("#popup-mpdal").modal("openModal");
            });

        }
    );

</script>

<!--<script>-->
<!--    require(-->
<!--        [-->
<!--            'jquery',-->
<!--            'Magento_Ui/js/modal/modal'-->
<!--        ],-->
<!--        function ($,-->
<!--                  modal) {-->
<!--            $('#login-form').submit(function () {-->
<!--                return false;-->
<!--            });-->
<!---->
<!--            var options = {-->
<!--                type: 'popup',-->
<!--                responsive: true,-->
<!--                innerScroll: true,-->
<!--                title: '',-->
<!--                buttons: [{-->
<!--                    text: $.mage.__('Close'),-->
<!--                    class: '',-->
<!--                    click: function () {-->
<!--                        this.closeModal();-->
<!--                    }-->
<!--                }]-->
<!--            };-->
<!---->
<!--            var popup = modal(options, $('#popup-mpdal'));-->
<!--            $("#send2").on('click', function () {-->
<!--                $("#popup-mpdal").modal("openModal");-->
<!--            });-->
<!---->
<!--        }-->
<!--    );-->
<!--</script>-->