<?php
namespace Magenest\StockStatus\Block\Adminhtml\Product\Attribute\Edit\Tabs;


class Ranges  extends \Magento\Backend\Block\Template{
    /**
     * @var array
     */
    //protected $_message = array();
    /**
     * @var string
     */
    //protected $_template = 'Magenest_StockStatus::catalog/product/attribute/ranges.phtml';

    protected function _prepareLayout(){
        $this->addChild(
            'add_button',
            'Magento\Backend\Block\Widget\Button',
            ['label' => __('Add New Rule'), 'class' => 'addRule', 'id' => 'add_new_qty_rule']
        );

        $this->addChild('options_box', 'Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Options\Option');

        $this->addChild(
            'import_button',
            'Magento\Backend\Block\Widget\Button',
            ['label' => __('Import Options'), 'class' => 'add', 'id' => 'import_new_defined_option']
        );
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
    /**
     * @return string
     */
    public function getAddButtonHtml(){
        return $this->getChildHtml('add_button');
    }

    /**
     * @return string
     */
    public function getOptionsBoxHtml(){
        return $this->getChildHtml('options_box');
    }

    /**
     * @param string $string
     * @return mixed
     */
    public function getCustomStockStatus($string = 'custom_stock_status'){
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $eavConfig = $objectManager->get('\Magento\Eav\Model\Config');
        $attribute = $eavConfig->getAttribute('catalog_product', $string);
        $options = $attribute->getSource()->getAllOptions();
        return $options;
    }
}

