<?php
$product = $block->getProduct();
$html = '';
foreach ($product as $id) {
    $html.="<span class=node >".$id."</span>";
}
?>
<div id="brand_status_show" value="0">

</div>
<script>
    function showProduct(){
        require(['jquery'],function($){
            $('#magenest_brand_product_filter_in_brand').val("1");
        <?php echo $block->getJsObjectName(). '.doFilter()' ?>
        });
    }
    function addProduct(){
        require(['jquery'],function($){
            $('#magenest_brand_product_filter_in_brand').val("0");
        <?php echo $block->getJsObjectName(). '.doFilter()' ?>
        });
    }
</script>