<?php
/**
 * @var $block \Magenest\ShopByBrand\Block\Brand\SideBar
 */

$datas = $block->getBrandInfo();
$baseBrandUrl = $block->getBaseBrandUrl();
$baseImageUrl = $block->getBaseImageUrl();
$i = 0;
?>

<div class="mn-brand-thum">
    <h3 class="brand-heading_title">Brand Thumbnail Widget</h3>
    <div class="mn-items">
        <?php foreach ($datas as $data) : ?>
            <?php if ($i < 6) : ?>
                <div class="mn-item">
                    <a class="brand-img" href='<?php echo $baseBrandUrl . '/' . $data['url_key'] ?>'>
                        <img src="<?php echo $block->getImage($data) ?>"/>
                    </a>
                </div>
                <?php $i++; ?>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
    <a class='brand_allview' href="<?php echo $baseBrandUrl ?>">
        View all
    </a>
</div>



