<?php
/**
 * Copyright © 2018 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Magenest\MapList\Block\Adminhtml\Map\Edit\Tab;

use Magento\Backend\Block\Widget\Form\Generic;
use Magento\Backend\Block\Widget\Tab\TabInterface;
use Magento\Backend\Block\Template\Context;
use Magento\Framework\Data\FormFactory;
use Magento\Framework\Registry;
use Magenest\MapList\Model\Status;

class AddOpeningHours extends Generic implements TabInterface{
    protected $categoryFactory;
    public function __construct(
        Context $context,
        Registry $registry,
        FormFactory $formFactory,
        Status $status,
        \Magento\Cms\Model\Wysiwyg\Config $wysiwygConfig,
        \Magenest\MapList\Model\CategoryFactory $categoryFactory,
        array $data
    ) {
        $this->categoryFactory = $categoryFactory;
        $this->_status = $status;
        $this->_wysiwygConfig = $wysiwygConfig;
//        $this->setAdvancedLabel("Add Tabs");
        parent::__construct($context, $registry, $formFactory, $data);
    }
    public function _prepareForm(){
        $model = $this->_coreRegistry->registry('maplist_map_edit');
        $dataModels = $model->getData();
        $data = [];
        foreach ($dataModels as $dataModel => $value){
            if($dataModel == 'opening_hours'){
                if ($value) {
                    $data = array_merge($data, json_decode($value, true));
                }
            }else{
                $data[$dataModel] = $value;
            }
        }
        $form = $this->_formFactory->create();
        $form->setHtmlIdPrefix('map_');

        $fieldset = $form->addFieldset(
            'opening_hours_fieldset',
            [
                'legend' => __('Opening Hours'),
            ]
        );
        if ($model->getId()) {
            $fieldset->addField(
                'map_id',
                'hidden',
                ['name' => 'map_id']
            );
        }
        $fieldset->addField(
            'is_use_default_opening_hours',
            'checkbox',
            [
                'name' => 'is_use_default_opening_hours',
                'label' => __('Use Default Hours'),
                'title' => __('Use Default Hours'),
                'required' => false,
                'onclick' => 'this.value = this.checked ? 1 : 0;',
                'checked' => isset($data['is_use_default_opening_hours']) ? $data['is_use_default_opening_hours'] : 0
            ]
        );
        $fieldset->addField(
            'opening_hours_sunday',
            'text',
            [
                'name' => 'opening_hours[opening_hours_sunday]',
                'label' => __('Sunday'),
                'title' => __('Sunday'),
                'required' => false
            ]
        );
        $fieldset->addField(
            'opening_hours_monday',
            'text',
            [
                'name' => 'opening_hours[opening_hours_monday]',
                'label' => __('Monday'),
                'title' => __('Monday'),
                'required' => false
            ]
        );
        $fieldset->addField(
            'opening_hours_tuesday',
            'text',
            [
                'name' => 'opening_hours[opening_hours_tuesday]',
                'label' => __('Tuesday'),
                'title' => __('Tuesday'),
                'required' => false
            ]
        );
        $fieldset->addField(
            'opening_hours_wednesday',
            'text',
            [
                'name' => 'opening_hours[opening_hours_wednesday]',
                'label' => __('Wednesday'),
                'title' => __('Wednesday'),
                'required' => false
            ]
        );
        $fieldset->addField(
            'opening_hours_thursday',
            'text',
            [
                'name' => 'opening_hours[opening_hours_thursday]',
                'label' => __('Thursday'),
                'title' => __('Thursday'),
                'required' => false
            ]
        );
        $fieldset->addField(
            'opening_hours_friday',
            'text',
            [
                'name' => 'opening_hours[opening_hours_friday]',
                'label' => __('Friday'),
                'title' => __('Friday'),
                'required' => false
            ]
        );
        $fieldset->addField(
            'opening_hours_saturday',
            'text',
            [
                'name' => 'opening_hours[opening_hours_saturday]',
                'label' => __('Saturday'),
                'title' => __('Saturday'),
                'required' => false
            ]
        );
        $form->setValues($data);
        $this->setForm($form);
        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }

    public function getTabLabel()
    {
        return __('Opening Hours');
    }

    public function getTabTitle()
    {
        return __('Opening Hours');
    }

    public function canShowTab()
    {
        return true;
    }

    public function isHidden()
    {
        return false;
    }
}