<?php
/** @var $block \Magenest\ShopByBrand\Block\Adminhtml\Dashboard\Index */
?>
<div class="row chart-total">
    <!--Table and divs that hold the pie charts-->
    <table class="columns">
        <tr>
            <td>
                <div id="piechart" style="width: 500px; height: 500px;"></div>
            </td>
            <td>
                <div id="barchart" ></div>
            </td>
        </tr>
    </table>
</div>


<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
    google.charts.load("current", {packages:["corechart"]});
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {

        var data = new google.visualization.DataTable();
        data.addColumn('string', 'brand');
        data.addColumn('number', 'qty');

        var dataOrder = new google.visualization.DataTable();
        dataOrder.addColumn('string', 'brand');
        dataOrder.addColumn('number', 'order');


        var params = <?php echo $block->getBrandQty(); ?>

        var order = <?php echo $block->getBrandOrder(); ?>


        data.addRows(params);
        dataOrder.addRows(order);

        var options = {
            title: 'Chart Qty Brand',
            legend: 'none',
            pieSliceText: 'label',
            slices: {  4: {offset: 0.2},
                12: {offset: 0.3},
                14: {offset: 0.4},
                15: {offset: 0.5},
            },
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));
        chart.draw(data, options);

        var barchart_options =
        {
            title: 'Chart Order Brand',
            lengnd: 'none',
            width:800,
            height:500,
            legend: 'none',
            pieSliceText: 'label'
        };
        var barchart = new google.visualization.BarChart(document.getElementById('barchart'));
        barchart.draw(dataOrder, barchart_options);
    }
</script>
