<h1><b>Requests Module</b></h1>
<hr>
<div class="row">
    <div class="col-m-6">
        <h2 ><b>Total Module</b></h2>
        <p>Numbers of module installed in Magento: <?php echo $block->getNumberModules(); ?></p>
        <p>Numbers of module installed in Magneto of another Vendor: <?php echo $block->getNumberModulesNotMagento(); ?></p>

    </div>

    <div class="col-m-6">
        <h2><b>Detail current</b></h2>
        <p>Numbers of Customers: <?php echo $block->getNumberCustomers() ?></p>
        <p>Products: <?php echo $block->getNumberProducts() ?></p>
        <p>Orders: <?php echo $block->getNumberOrders() ?></p>
        <p>Invoices: <?php echo $block->getNumberInvoices() ?></p>
        <p>Creditmemos: <?php echo $block->getNumberCustomers() ?></p>

    </div>
</div>
