<?php
//@codingStandardsIgnoreFile

/** @var \Magenest\Blog\Block\Sidebar\TagCloud $block */
//$max = $block->getMaxPopularity() + 1;
?>
<div class="block blog__sidebar-tag-cloud">
    <div class="block-content">
        <?php foreach ($block->getCollection() as $tag):
                if(!$block->getEmptyTag($tag->getId())):
            ?>
            <a class="tag-sidebar" href="<?= $tag->getUrl() ?>">
                <?= $tag->getName() ?>
            </a>
        <?php   endif;
        endforeach ?>
    </div>
</div>

<style>
    .tag-sidebar{
        display: inline-block;
        border: 1px solid #999;
        padding: 0px 15px;
        text-transform: capitalize;
        color: #999;
        line-height: 30px;
        white-space: nowrap;
        margin-right: 5px;
        margin-bottom: 10px;
        text-align: center;
        font-size: 13px;
    }
</style>
