<?php
//@codingStandardsIgnoreFile

/** @var \Magenest\Blog\Block\Post\Meta $block */

$post = $block->getPost();
?>
<footer class="blog__post-footer">
    <?php if ($post->getCategories()->count()): ?>
        <span class="blog__post-footer-categories">
            <i class="fa fa-fw fa-folder-open"></i>
            <?php foreach ($post->getCategories() as $category): ?>
                <a href="<?= $category->getUrl() ?>" rel="category tag"><?= $category->getName() ?></a>
            <?php endforeach ?>
        </span>
    <?php endif ?>
    <?php if ($post->getTags()->count()): ?>
        <span class="blog__post-footer-tags">
                <i class="fa fa-fw fa-tags"></i>
            <?php foreach ($post->getTags() as $tag): ?>
                <a href="<?= $tag->getUrl() ?>" rel="tag"><?= $tag->getName() ?></a>
            <?php endforeach ?>
        </span>
    <?php endif ?>
        <span class="blog__post-footer-company">
            <i class="fa fa-fw fa-folder-company"></i>
            <a href="http://magenest.com" rel="company tag" target="_blank" style="color:#a3a3a3"><?php echo __('Powered by Magenest') ?></a>
        </span>
</footer>