<?php
//@codingStandardsIgnoreFile

/** @var \Magenest\Blog\Block\Post\Meta $block */

$post = $block->getPost();
?>
<p class="blog__post-meta">
    <time class="blog__post-meta-time" itemprop="datePublished">
        <i class="fa fa-fw fa-calendar"></i>
        <?= $block->toDateFormat($post->getCreatedAt()) ?>
    </time>

    <span class="blog__post-meta-author" itemprop="author" itemscope=""
          itemtype="http://schema.org/Person">
        <i class="fa fa-fw fa-user"></i>
        <span itemprop="name">
            <a  id="click-me-<?php echo $block->getPost()->getId()."-".$block->getAuthor()->getId() ?>"><?= 'Author: '.$block->getAuthor()->getDisplayName()?></a>
        </span>
    </span>

    <?php if ($block->getCommentProvider() == 'disqus'): ?>
        <span class="blog__post-meta-comments">
        <i class="fa fa-fw fa-comments"></i>
        <span class="disqus-comment-count"
              data-disqus-identifier="<?= $block->getPost()->getUrlKey() ?>"><?= __('0 Comments') ?></span>
    </span>
    <?php endif ?>

    <?php if ($block->getCommentProvider() == 'facebook'): ?>
        <span class="blog__post-meta-comments">
        <i class="fa fa-fw fa-comments"></i>
        <span class="fb-comments-count" data-href="<?= $block->getPost()->getUrl() ?>"></span> Comments
    </span>
    <?php endif ?>


    <span class="blog__post-meta-view">
                <i class="fa fa-fw fa-eye"></i>
        <?= 'View: '.$block->getNumberVisits();?>
    </span>
</p>


<div id="popup-mpdal-<?php echo $block->getPost()->getId()."-".$block->getAuthor()->getId() ?>" style="display:none;">
    <div class="avatar_author">
        <img src="<?php echo $this->getUrl('pub/media').$block->getAuthor()->getImage(); ?>">
    </div>
    <div class="information_author">
        <?php echo $block->getAuthor()->getInformation() ?>
    </div>
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Author',
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-mpdal-<?php echo $block->getPost()->getId()."-".$block->getAuthor()->getId() ?>'));
            $("#click-me-<?php echo $block->getPost()->getId()."-".$block->getAuthor()->getId() ?>").on('click',function(){
                $("#popup-mpdal-<?php echo $block->getPost()->getId()."-".$block->getAuthor()->getId() ?>").modal("openModal");
            });

        }
    );
</script>
<style>
    .avatar_author {
        float: left;
        width: 29%;
    }
    .information_author {
        overflow: hidden;
    }

</style>