<?php
/**
 * Product list template
 *
 * @var $block \Magenest\ShopByBrand\Block\Brand\Index\Listing
 */
?>
<?php
$router = $block->getRouter();
$getBrandUrl = $block->getBrandUrl();
$baseMediaUrl = $block->getBaseMediaUrl();
$baseStaticUrl = $block->getBaseStaticUrl();
$allBrands = $block->getAllBrand();
$show = $block->getBrandConfig();
$show = $block->getBrandConfig();
?>

<div class="ui-widget">
    <input id="brandsearch" placeholder="Search by name" autocomplete="off" autocorrect="off" autofocus="autofocus">
</div>

<div class="mn-view-list mn-view-list_style1">
    <div class="mn-items">
        <div id="searchbrand" class="  mn-items-content">
        </div>
    </div>
</div>

<script type="text/javascript" charset="utf-8">
    var searchWidth = 35;
    var brands = [<?php foreach ($allBrands as $allBrand) {
        echo '{"n":"'.$allBrand['name'].'","k":"'.$allBrand['url_key'].'","i":"'.$allBrand['logo'].'"},';
} ?>]
    var brandIndex = 0;
    require(['jquery'], function($) {
        $('#brandsearch').on("input", null, null, function (el) {
            $('#searchbrand').html('');
            var vsearch =document.getElementById('brandsearch').value;
            if(vsearch.length>0) {
                var count = 0;
                for (var i = 0; i < brands.length; i++) {
                    if (brands[i].n.toLowerCase().search(el.target.value.toLowerCase()) != -1) {
                        count++;
                        if (brands[i].i != "") {
                            $html = "<div class='mn-item '>" +
                                "<a class='brand-img' href=<?php echo $getBrandUrl ?>" + brands[i].k + " >" +
                                "<img src='<?php echo $baseMediaUrl . $router::ROUTER_MEDIA ?>" + brands[i].i + " ' alt=brands[i].n /> <span class='brand-name'>" +
                                "" + brands[i].n +
                                "</span></a> </div>";
                            $('#searchbrand').append($html);
                        } else {
                            $html = "<div class='mn-item '>" +
                                "<a class='brand-img' href=<?php echo $getBrandUrl ?>" + brands[i].k + " >" +
                                "<img src='<?php echo $baseStaticUrl . \Magenest\ShopByBrand\Model\Config\Router::ROUTER_STATIC?>'/> <span class='brand-name'>" +
                                "" + brands[i].n +
                                "</span></a> </div>";
                            $('#searchbrand').append($html);
                        }
                    }
                }
            }
            if(count==0){
                $('#searchbrand').append('<strong>There is no any result match input value</strong>');
            }
            brandIndex = 0;
            if (count) {
                $('#searchbrand li').first().addClass('selected');
            }
        });
        var click = $('body').first().click(function (event) {
            if (event.target.id == 'brandsearch' || event.target.id == 'searchbrand')
                return;
            else $('#searchbrand').html('');
        });

        $('#brandsearch').keyup(function (event) {
            if (event.keyCode == 38 || event.keyCode == 40) {
                if ($F('brandsearch') == '' && !$$('#searchbrand li').length)
                    brands.each(function (el) {
                        $('searchbrand').insert('<li  onclick="redirect(\'' + el.k + '\',\'' + el.n + '\')">' + el.n + '</li>');
                    });
                $$('#searchbrand li')[brandIndex].removeClassName('selected');
                getSelectedIndex(event.keyCode);
                $$('#searchbrand li')[brandIndex].addClassName('selected');
                searchScroll();
                $('brandsearch').value = $$('#searchbrand li.selected').first().textContent;
            }
            if (event.keyCode == 13) {
                $('#brandsearch').value = '';
                if ($('#searchbrand li.selected').first())
                    $('#searchbrand li.selected').first().click();
            }
        });
        window.searchScroll = function() {
            if ($('searchbrand').scrollTop > brandIndex * searchWidth)
                $('searchbrand').scrollTop = brandIndex * searchWidth;
            else if ($('searchbrand').scrollTop + 8 * searchWidth < brandIndex * searchWidth)
                $('searchbrand').scrollTop = brandIndex * searchWidth - 7 * searchWidth;
        }

        window.getSelectedIndex = function(keycode) {
            var length = $$('#searchbrand li').length;
            if (keycode == 38 && brandIndex == 0)
                brandIndex = length - 1;
            else if (keycode == 40 && brandIndex == (length - 1))
                brandIndex = 0;
            else if (keycode == 38)
                brandIndex--;
            else if (keycode == 40)
                brandIndex++;
        }

        window.redirect = function(url_key, name) {
            $('brandsearch').value = name;
            window.location.href = '<?php echo $getBrandUrl ?>' + url_key;
        }
    });
</script>